/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : MyGrammarTest.g
 *     -                            On : 2024-11-17 16:19:59
 *     -                 for the lexer : MyGrammarTestLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
MyGrammarTestLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pMyGrammarTestLexer, which is returned from a call to MyGrammarTestLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pMyGrammarTestLexer are  as follows:
 *
 *  - 
 void
      pMyGrammarTestLexer->T__50(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__51(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__52(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__53(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__54(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__55(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__56(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__57(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__58(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__59(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__60(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__61(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__62(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__63(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__64(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__65(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__66(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__67(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__68(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__69(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__70(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__71(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__72(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__73(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__74(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__75(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__76(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__77(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__78(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__79(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__80(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__81(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__82(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__83(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__84(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__85(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__86(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__87(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__88(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__89(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__90(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__91(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__92(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__93(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__94(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__95(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__96(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__97(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->T__98(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->LITERAL(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->BOOL_LITERAL(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->BITS_LITERAL(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->HEX_LITERAL(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->HEX_DIGIT(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->DEC_LITERAL(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->CHAR(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->STRING_LIT(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->ESC_SEQ(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->IDENTIFIER(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->WS(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->LINE_COMMENT(pMyGrammarTestLexer)
 *  - 
 void
      pMyGrammarTestLexer->Tokens(pMyGrammarTestLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_MyGrammarTestLexer_H
#define _MyGrammarTestLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct MyGrammarTestLexer_Ctx_struct MyGrammarTestLexer, * pMyGrammarTestLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
MyGrammarTestLexer

 */
struct MyGrammarTestLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__50)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__51)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__52)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__53)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__54)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__55)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__56)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__57)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__58)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__59)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__60)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__61)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__62)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__63)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__64)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__65)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__66)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__67)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__68)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__69)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__70)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__71)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__72)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__73)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__74)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__75)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__76)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__77)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__78)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__79)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__80)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__81)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__82)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__83)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__84)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__85)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__86)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__87)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__88)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__89)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__90)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__91)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__92)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__93)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__94)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__95)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__96)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__97)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mT__98)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mLITERAL)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mBOOL_LITERAL)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mBITS_LITERAL)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mHEX_LITERAL)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mHEX_DIGIT)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mDEC_LITERAL)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mCHAR)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mSTRING_LIT)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mESC_SEQ)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mLINE_COMMENT)	(struct MyGrammarTestLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct MyGrammarTestLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct MyGrammarTestLexer_Ctx_struct * ctx);
    void	    (*free)   (struct MyGrammarTestLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pMyGrammarTestLexer MyGrammarTestLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pMyGrammarTestLexer MyGrammarTestLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define T__65      65
#define T__66      66
#define T__67      67
#define T__68      68
#define T__69      69
#define T__70      70
#define T__71      71
#define T__72      72
#define T__73      73
#define T__74      74
#define T__75      75
#define T__76      76
#define T__77      77
#define T__78      78
#define T__79      79
#define T__80      80
#define T__81      81
#define T__82      82
#define T__83      83
#define T__84      84
#define T__85      85
#define T__86      86
#define T__87      87
#define T__88      88
#define T__89      89
#define T__90      90
#define T__91      91
#define T__92      92
#define T__93      93
#define T__94      94
#define T__95      95
#define T__96      96
#define T__97      97
#define T__98      98
#define Args      4
#define Argument      5
#define ArrayAccess      6
#define ArrayType      7
#define BITS_LITERAL      8
#define BOOL_LITERAL      9
#define BlockStatement      10
#define BodySig      11
#define Braces      12
#define BreakStatement      13
#define BuiltinType      14
#define CHAR      15
#define CallExpr      16
#define Condition      17
#define CustomType      18
#define DEC_LITERAL      19
#define DoStatement      20
#define ESC_SEQ      21
#define Elems      22
#define Else      23
#define Expression      24
#define ExpressionStatement      25
#define FuncDef      26
#define FuncSignature      27
#define FunctionCall      28
#define HEX_DIGIT      29
#define HEX_LITERAL      30
#define IDENTIFIER      31
#define Identifier      32
#define IfStatement      33
#define Indexer      34
#define Indices      35
#define LINE_COMMENT      36
#define LITERAL      37
#define ListArgDefs      38
#define ListExpr      39
#define ListIdentifier      40
#define Literal      41
#define STRING_LIT      42
#define Source      43
#define SourceItem      44
#define Then      45
#define TypeRef      46
#define VarsDefenition      47
#define WS      48
#define WhileStatement      49
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for MyGrammarTestLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
